package de.vptr.aimathtutor.repository;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.time.LocalDateTime;

import org.junit.jupiter.api.Test;

import de.vptr.aimathtutor.dto.AiConfigDto.ConfigCategory;
import de.vptr.aimathtutor.dto.AiConfigDto.ConfigType;
import de.vptr.aimathtutor.entity.AiConfigEntity;
import de.vptr.aimathtutor.entity.AiInteractionEntity;
import de.vptr.aimathtutor.entity.CommentEntity;
import de.vptr.aimathtutor.entity.CommentFlagEntity;
import de.vptr.aimathtutor.entity.ExerciseEntity;
import de.vptr.aimathtutor.entity.LessonEntity;
import de.vptr.aimathtutor.entity.StudentSessionEntity;
import de.vptr.aimathtutor.entity.UserEntity;
import de.vptr.aimathtutor.entity.UserGroupEntity;
import de.vptr.aimathtutor.entity.UserGroupMetaEntity;
import de.vptr.aimathtutor.entity.UserRankEntity;
import io.quarkus.test.TestTransaction;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;

/**
 * Integration tests verifying that {@code created} and {@code last_edit}
 * timestamps are generated by the database and never require manual assignment.
 *
 * <p>
 * Every entity must have {@code created} populated automatically on insert
 * and {@code last_edit} populated automatically on update via database
 * defaults and triggers.
 */
@QuarkusTest
class DbTimestampIT {

    @Inject
    EntityManager em;

    @Inject
    UserRankRepository userRankRepository;

    @Inject
    UserRepository userRepository;

    @Inject
    LessonRepository lessonRepository;

    @Inject
    ExerciseRepository exerciseRepository;

    @Inject
    CommentRepository commentRepository;

    @Inject
    CommentFlagRepository commentFlagRepository;

    @Inject
    UserGroupRepository userGroupRepository;

    @Inject
    UserGroupMetaRepository userGroupMetaRepository;

    @Inject
    StudentSessionRepository studentSessionRepository;

    @Inject
    AiInteractionRepository aiInteractionRepository;

    @Inject
    AiConfigRepository aiConfigRepository;

    // ------------------------------------------------------------------
    // AiInteractionEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void aiInteractionTimestampsAreDbGenerated() {
        final var interaction = new AiInteractionEntity();
        interaction.eventType = "TEST";
        interaction.feedbackType = "HINT";

        this.aiInteractionRepository.persist(interaction);
        this.em.flush();

        assertNotNull(interaction.created, "AiInteractionEntity.created must be generated by the DB");
        assertNull(interaction.lastEdit, "AiInteractionEntity.lastEdit must be null before update");

        interaction.feedbackMessage = "updated";
        this.em.flush();

        assertNotNull(interaction.lastEdit, "AiInteractionEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // ExerciseEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void exerciseTimestampsAreDbGenerated() {
        final var user = this.createUser("exercise_user");
        final var exercise = new ExerciseEntity();
        exercise.title = "Test";
        exercise.content = "Content";
        exercise.user = user;

        this.exerciseRepository.persist(exercise);
        this.em.flush();

        assertNotNull(exercise.created, "ExerciseEntity.created must be generated by the DB");
        assertNull(exercise.lastEdit, "ExerciseEntity.lastEdit must be null before update");

        exercise.title = "Updated";
        this.em.flush();

        assertNotNull(exercise.lastEdit, "ExerciseEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // UserEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void userTimestampsAreDbGenerated() {
        final var user = new UserEntity();
        user.username = "timestamp_user";
        user.password = "secret";
        user.rank = this.userRankRepository.findById(1L);

        this.userRepository.persist(user);
        this.em.flush();

        assertNotNull(user.created, "UserEntity.created must be generated by the DB");
        assertNull(user.lastEdit, "UserEntity.lastEdit must be null before update");

        user.password = "new_secret";
        this.em.flush();

        assertNotNull(user.lastEdit, "UserEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // CommentEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void commentTimestampsAreDbGenerated() {
        final var user = this.createUser("comment_user");
        final var exercise = this.createExercise(user, "Comment Exercise");
        final var comment = new CommentEntity();
        comment.content = "Nice!";
        comment.exercise = exercise;
        comment.user = user;

        this.commentRepository.persist(comment);
        this.em.flush();

        assertNotNull(comment.created, "CommentEntity.created must be generated by the DB");
        assertNull(comment.lastEdit, "CommentEntity.lastEdit must be null before update");

        comment.content = "Updated";
        this.em.flush();

        assertNotNull(comment.lastEdit, "CommentEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // CommentFlagEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void commentFlagTimestampsAreDbGenerated() {
        final var user = this.createUser("flag_user");
        final var exercise = this.createExercise(user, "Flag Exercise");
        final var comment = new CommentEntity();
        comment.content = "Flag me";
        comment.exercise = exercise;
        comment.user = user;
        this.commentRepository.persist(comment);
        this.em.flush();

        final var flag = new CommentFlagEntity();
        flag.comment = comment;
        flag.flagger = user;

        this.commentFlagRepository.persist(flag);
        this.em.flush();

        assertNotNull(flag.created, "CommentFlagEntity.created must be generated by the DB");
        assertNull(flag.lastEdit, "CommentFlagEntity.lastEdit must be null before update");

        this.em.createNativeQuery("UPDATE comment_flags SET id = id WHERE id = :id")
                .setParameter("id", flag.id)
                .executeUpdate();
        this.em.flush();
        this.em.refresh(flag);

        assertNotNull(flag.lastEdit, "CommentFlagEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // UserGroupEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void userGroupTimestampsAreDbGenerated() {
        final var group = new UserGroupEntity();
        group.name = "TestGroup";

        this.userGroupRepository.persist(group);
        this.em.flush();

        assertNotNull(group.created, "UserGroupEntity.created must be generated by the DB");
        assertNull(group.lastEdit, "UserGroupEntity.lastEdit must be null before update");

        group.name = "UpdatedGroup";
        this.em.flush();

        assertNotNull(group.lastEdit, "UserGroupEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // UserGroupMetaEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void userGroupMetaTimestampsAreDbGenerated() {
        final var user = this.createUser("ugm_user");
        final var group = new UserGroupEntity();
        group.name = "UGMGroup";
        this.userGroupRepository.persist(group);
        this.em.flush();

        final var meta = new UserGroupMetaEntity();
        meta.user = user;
        meta.group = group;

        this.userGroupMetaRepository.persist(meta);
        this.em.flush();

        assertNotNull(meta.created, "UserGroupMetaEntity.created must be generated by the DB");
        assertNull(meta.lastEdit, "UserGroupMetaEntity.lastEdit must be null before update");

        this.em.createNativeQuery("UPDATE user_groups_meta SET id = id WHERE id = :id")
                .setParameter("id", meta.id)
                .executeUpdate();
        this.em.flush();
        this.em.refresh(meta);

        assertNotNull(meta.lastEdit, "UserGroupMetaEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // LessonEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void lessonTimestampsAreDbGenerated() {
        final var lesson = new LessonEntity();
        lesson.name = "Algebra";

        this.lessonRepository.persist(lesson);
        this.em.flush();

        assertNotNull(lesson.created, "LessonEntity.created must be generated by the DB");
        assertNull(lesson.lastEdit, "LessonEntity.lastEdit must be null before update");

        lesson.name = "Geometry";
        this.em.flush();

        assertNotNull(lesson.lastEdit, "LessonEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // UserRankEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void userRankTimestampsAreDbGenerated() {
        final var rank = new UserRankEntity();
        rank.name = "TimestampRank";

        this.userRankRepository.persist(rank);
        this.em.flush();

        assertNotNull(rank.created, "UserRankEntity.created must be generated by the DB");
        assertNull(rank.lastEdit, "UserRankEntity.lastEdit must be null before update");

        rank.name = "UpdatedRank";
        this.em.flush();

        assertNotNull(rank.lastEdit, "UserRankEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // StudentSessionEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void studentSessionTimestampsAreDbGenerated() {
        final var user = this.createUser("session_user");
        final var exercise = this.createExercise(user, "Session Exercise");
        final var session = new StudentSessionEntity();
        session.sessionId = "sess-timestamp";
        session.user = user;
        session.exercise = exercise;
        session.startTime = LocalDateTime.now();

        this.studentSessionRepository.persist(session);
        this.em.flush();

        assertNotNull(session.created, "StudentSessionEntity.created must be generated by the DB");
        assertNull(session.lastEdit, "StudentSessionEntity.lastEdit must be null before update");

        session.actionsCount = 42;
        this.em.flush();

        assertNotNull(session.lastEdit, "StudentSessionEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // AiConfigEntity
    // ------------------------------------------------------------------

    @Test
    @TestTransaction
    void aiConfigTimestampsAreDbGenerated() {
        final var config = new AiConfigEntity();
        config.configKey = "test.timestamp.key";
        config.configValue = "v1";
        config.configType = ConfigType.STRING;
        config.category = ConfigCategory.GENERAL;

        this.aiConfigRepository.persist(config);
        this.em.flush();

        assertNotNull(config.created, "AiConfigEntity.created must be generated by the DB");
        assertNull(config.lastEdit, "AiConfigEntity.lastEdit must be null before update");

        config.configValue = "v2";
        this.em.flush();

        assertNotNull(config.lastEdit, "AiConfigEntity.lastEdit must be generated by the DB on update");
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    private UserEntity createUser(final String username) {
        final var user = new UserEntity();
        user.username = username;
        user.password = "secret";
        user.rank = this.userRankRepository.findById(1L);
        this.userRepository.persist(user);
        return user;
    }

    private ExerciseEntity createExercise(final UserEntity user, final String title) {
        final var exercise = new ExerciseEntity();
        exercise.title = title;
        exercise.content = "test content";
        exercise.user = user;
        this.exerciseRepository.persist(exercise);
        return exercise;
    }
}
